// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArF-2Bgz3vCzV6p9o8JpBGxJ4h9_3iBIk',
    appId: '1:33754482907:web:c970530f112e1c4410a4fe',
    messagingSenderId: '33754482907',
    projectId: 'fruits-hub-268fc',
    authDomain: 'fruits-hub-268fc.firebaseapp.com',
    storageBucket: 'fruits-hub-268fc.firebasestorage.app',
    measurementId: 'G-J68PPC0TGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr1B9hpevnD-eVlbYYhmIxPAaTUoNCBB4',
    appId: '1:33754482907:android:18c7e43b35b4ea9910a4fe',
    messagingSenderId: '33754482907',
    projectId: 'fruits-hub-268fc',
    storageBucket: 'fruits-hub-268fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIVF9g0FrLsxImDLDuDD2qvw-q_Eocngw',
    appId: '1:33754482907:ios:e7d8acea8ac9bef210a4fe',
    messagingSenderId: '33754482907',
    projectId: 'fruits-hub-268fc',
    storageBucket: 'fruits-hub-268fc.firebasestorage.app',
    iosBundleId: 'com.example.fruitsECommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIVF9g0FrLsxImDLDuDD2qvw-q_Eocngw',
    appId: '1:33754482907:ios:e7d8acea8ac9bef210a4fe',
    messagingSenderId: '33754482907',
    projectId: 'fruits-hub-268fc',
    storageBucket: 'fruits-hub-268fc.firebasestorage.app',
    iosBundleId: 'com.example.fruitsECommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArF-2Bgz3vCzV6p9o8JpBGxJ4h9_3iBIk',
    appId: '1:33754482907:web:20f2ecfa35a4851610a4fe',
    messagingSenderId: '33754482907',
    projectId: 'fruits-hub-268fc',
    authDomain: 'fruits-hub-268fc.firebaseapp.com',
    storageBucket: 'fruits-hub-268fc.firebasestorage.app',
    measurementId: 'G-7M2WT4RX55',
  );
}
